### ISSUE TITLE
link tags in body text being stripped of attributes

### ISSUE THREAD

**Issue by mrandrewmills** [pkerspe/ckeditor-bootstrap-collapsibleItem#10]
Greetings, pkerspe

I'm using your ckeditor-bootstrap-accordionlist and ckeditor-bootstrap-collapsibleitem plugins with CKEditor 4.7.2 in a CommonSpot CMS, and I'm experiencing an issue with linked text in the body text portion of the collapsible item.  I can successfully create text with a hyperlink (e.g. `<a href="https://www.google.com">this link</a>`), and publish/save it successfully, but any subsequent edits which reload the text in CKEditor cause the attributes of the link tag within the collapsible item to be removed, leaving me with an empty tag (e.g. `<a>this link</a>`).  

Links within text paragraphs outside of the collapsible item body text are not changed and remain intact.

I'm also able to trigger this "link attribute stripping" issue with a standalone instance of CKEditor (also 4.7.2) and the two plugins and their dependencies, by toggling into and out of the source editing mode with the Source button on the CKEditor toolbar, so I know it's independent from the saving/loading of data within the CMS.  I'm seeing this issue on Windows 10/Google Chrome 63.0.3239.132 and Firefox ESR 52.5.3 (also Windows 10).

If there's anything else I can provide to help resolve this issue, please let me know.

Thank you,

Andrew

**Comment by mrandrewmills** [comment]
Quick update for you-- 

This appears related to the modification of the allowedContent value (line 34 of plugin.js) discussed in Issue #9.  I've altered my local code accordingly, and it is working, but it looks like CKEditor may still be providing a previous version of your plugin for those *not* using the CKBuilder to get their plugin downloads.

**Comment by pkerspe** [comment]
@mrandrewmills thanks for your report. I Updated the versions on the ckeditor site to the latest tags of the plugins. Could you please try again and report back so we can close the issue?

**Comment by mrandrewmills** [comment]
You're most welcome. Thank you for the quick turnaround. 

I ran diff against downloaded .zips from github and ckeditor, and only delta I see is version reference in the README.md file (on the ckeditor download side). From a code perspective, everything is identical, so I'm good with you considering this closed, if you are.
