### ISSUE TITLE
Unable to insert other plugins like codesnipet inside the item body

### ISSUE THREAD

**Issue by pupattan** [pkerspe/ckeditor-bootstrap-collapsibleItem#12]
Unable to insert other plugins like codesnipet inside the item body
Its disabling plugins like "codesnnipet" when i click inside the item body

**Comment by pkerspe** [comment]
you need to edit plugin.js and add your needed html elements to the list of "allowedContent" (in the content block) separated by ";":

`content: {`
`                    selector: '.collapsible-item-body',`
`                    allowedContent: 'p;br;span(*)[*];ul;ol;li;strong;em;u;table(*)[*];tbody;thead;tr;td;th;hr;a;a[*];a(*)[*];img(*)[*];'`
`                }`
