### ISSUE TITLE
Cannot edit title after switching back from source view

### ISSUE THREAD

**Issue by adriano66** [pkerspe/ckeditor-bootstrap-collapsibleItem#2]
WIN7, Chrome 58.0.3029.110 (64-bit), Firefox 53.0.3 (32-bit)

Easiest way to reproduce the bug.
-  Add new collapsible element
-  Switch to source
-  Switch back to WYSIWYG

I was using this build http://ckeditor.com/builder/76330dc789253a1b6b9955786dbe3379

![obraz](https://cloud.githubusercontent.com/assets/3438696/26692828/608e2bc2-4702-11e7-995a-b509c0ab4355.png)

**Comment by adriano66** [comment]
I've sent the fix but I have no prior experience with ckeditor plugins so it might not be the best solution :)

**Comment by pkerspe** [comment]
Thanks a lot Adriano for the pull-request. I will investigate the changes this weekend and merge if approved.

**Comment by pkerspe** [comment]
pull request is merged, closing this ticket now
