### ISSUE TITLE
Using CTRL+V in title field

### ISSUE THREAD

**Issue by adriano66** [pkerspe/ckeditor-bootstrap-collapsibleItem#4]
WIN10, Firefox 53.0.3 (64 bit)
Using CTRL+V in title field duplicates \<a\> nodes in the title, and places pasted text outside of those \<a\> nodes.

I was using this build http://ckeditor.com/builder/76330dc789253a1b6b9955786dbe3379

![obraz](https://cloud.githubusercontent.com/assets/3438696/26816973/ca9e93ae-4a94-11e7-9700-2cd191128fc9.png)

![obraz](https://cloud.githubusercontent.com/assets/3438696/26817056/24f478e6-4a95-11e7-81b2-438d17eb41b8.png)

EDIT: I found out that is might actually be an issue with the pasting into the widget editable fields and not just this plugin. In that case, this issue is no longer relevant for the plugin as the problem lays somewhere else.

**Comment by adriano66** [comment]
I managed to fix this issue by setting editable element styles to { display: block; } as it turns out pasting into inline elements in ckeditor is causing this issue.

**Comment by pkerspe** [comment]
merged pull request so closing this ticket now
