### ISSUE TITLE
Can't change panel title after save

### ISSUE THREAD

**Issue by santaclaus21** [pkerspe/ckeditor-bootstrap-collapsibleItem#6]
After any save I can't edit title of collapsilable emenent (?), and there is no yellow frame on this. There is a conflict with **accordian list** plugin.
![image](https://user-images.githubusercontent.com/1121662/28311593-6f968650-6bb0-11e7-95fe-f0eba918bf42.png)

**Comment by pkerspe** [comment]
Hi, can you please specify the version used to replicate this issue?

**Comment by santaclaus21** [comment]
Latest CKEditor 4.71, latest both plugins. The problem is after reinitialize ckeditor (after first close ckeditor).
I can't make focus on title.

**Comment by pkerspe** [comment]
I just update the plugins some minutes ago in CKBuilder. would you be willing to update an try again please?

**Comment by santaclaus21** [comment]
Hm... I don't see new commits on github? Only in CKBuilder? I can't find it now in CKBuilder (?)

![image](https://user-images.githubusercontent.com/1121662/28313482-4daebf7e-6bb7-11e7-9c4a-2f53d879d896.png)

**Comment by pkerspe** [comment]
I created a new release in git only with the latest community contributions.
Indeed I cannot see it anymore in builder myself now after I uploaded the latest version. No idea what happened there. This whole builder is not very transparent, so no idea how to debug why it does not show up anymore

**Comment by pkerspe** [comment]
seems to work again now, plugins showing up in builder again...maybe just some packaging delay

**Comment by santaclaus21** [comment]
Give me 5 minuts and I will check new version.

**Comment by pkerspe** [comment]
still seems to have some issues. At least the icon for accordeon list is still missing...no idea how the packaging logic for this damn icons works :-(

**Comment by santaclaus21** [comment]
But focus on title is working now. There is only no icons in CKBuilder.
May you commit these changes on Github? Then I will use as extra plugin. 
What about allow to change link (panel) color change (only text color)?

Ok, I've moved icon files to build version and it's working.

**Comment by pkerspe** [comment]
when I download customized version from builder I can see the icon for ckeditor-bootstrap-collapsibleItem but not for ckeditor-bootstrap-accordion-list. I just uploaded a new version 0.5.1 to builder with a renamed icon for accordion. Will need to wait for the site to update to new plugin

**Comment by pkerspe** [comment]
since focus is working now, I close this issue

**Comment by santaclaus21** [comment]
May you update github repository? When I use as extra plugin then I will change ACF rules myself (link color #5 ). When plugin is merged by builder, it's not easy..

**Comment by pkerspe** [comment]
github is the source, it always has the latest code  (I upload to builder using the zip from github, so builder never has a newer src than github)
When you have any changes please fork the plugin, add you changes and send pull request. I will be happy to merge your development if it is not to use case specifc and in a generic way

**Comment by santaclaus21** [comment]
What about "focus" trouble, where was this fixed? Because I don't see any commits today (?)

**Comment by pkerspe** [comment]
it was already fixed/merged from pull request some weeks ago, but I did not create a new release yet
