### ISSUE TITLE
Bootstrap tables vs ACF

### ISSUE THREAD

**Issue by santaclaus21** [pkerspe/ckeditor-bootstrap-collapsibleItem#7]
There is not possible to stylize table with bootstrap classes because ACF rules of plugin doesn't allow:
eg. table class, rowspan, colspan even if I allow this global in CKEditor.

**Comment by pkerspe** [comment]
Hi Santa :-)
which table are you referring to?
And why would you like to style something in ckeditor manually rather than using the site css to format ckeditor content in a organized manner in the fronted?
How do you want to "stylize" colspan and rowspan in css?
Or are you saying that httml attributes are not allowed in general?

Feel free to create a fork apply your desired changes and create a pull request. I will try to review it ASAP.

**Comment by pkerspe** [comment]
on second though: not sure which tables you are refering too, the plugin does not use tabes

But you can edit plugin.js and update the lines starting with:
`allowedContent: `
And add the required tags and properties you want to allow

**Comment by santaclaus21** [comment]
I was trying add ACF rules without success. 
1) I am adding bootstrap classes to table, it looks fine:
![image](https://user-images.githubusercontent.com/1121662/28427110-6d0d596a-6d75-11e7-8efd-bba1aecdf882.png)

2) I am going to source editor, everything is fine:
![image](https://user-images.githubusercontent.com/1121662/28427148-8b80ca9e-6d75-11e7-856b-2da58ff841ed.png)

3) I am returning to standard editor... and there is no classes on table
![image](https://user-images.githubusercontent.com/1121662/28427213-c2d67494-6d75-11e7-99ec-f22f9daeff2d.png)

![image](https://user-images.githubusercontent.com/1121662/28427252-dcdde822-6d75-11e7-801f-22c70e7af3b4.png)

So, any ACF changes doesn't solved my problem. Everything inline styles, classes are going to be remove (?!). I have no idea what is a reason. 

My CKE ACF rule:
```
  config.allowedContent = 'button(*)[*]{*}; strike(*)[*]{*}; script(*)[*]{*}; *(*); td th[colspan,rowspan,nowrap]{border,border-width,vertical-align,width,color,white-space}; table[align, cellpadding, cellspacing, border]{border,border-width,width,margin}; img[alt,!src, border, title, contenteditable]{width,height,float,margin,margin-left,margin-right,margin-top,margin-bottom,border-width}; span iframe embed object param form input select textarea[*]; article{display}; div sup sub header footer section article span table tr td th ol li p h1 h2 h3 h4 h5{list-style,list-style-type,font-weight,text-align,text-decoration,color,white-space}; ol ul[start][type]; a[*]{font-weight,text-decoration}; *[id]; *[contenteditable,data-animspeedid,data-autostartid,data-openonclickid,data-pictheightid,data-showcontrolid,data-showtitleid,data-slideshowid,data-speedid,data-transitiontypeid]; figure figcaption b i u div blockquote strong hr th em ol ul;';
```

**Comment by santaclaus21** [comment]
The same rules (ACF) outside collapsilable plugin are working fine for me.
Ok. I've found it. The problem is in that case "bootstrap accordian" plugin.

**IMHO:** In that case collapsilableItem ACF shoud overwrite accordian rules if is that possible.

**Comment by santaclaus21** [comment]
RESOLVED by:
collapsilableItem/plugin.js:
```
:34
allowedContent: '*{color};div(*)[*];p;br;span[*];ul;ol;li;strong;em;u;table(*)[*];tbody;thead;tr;td th[colspan,rowspan,nowrap]{border,border-width,vertical-align,width,color,white-space};hr;a;a(!href,*)[*];img(*)[*];'

:37
allowedContent: 'div(*)[*];h4(!collapsible-item*,panel*)[*];a(!collapsible-item*,collapsed,panel*)[*];span(!glyphicon*)[*];img(*)[*]',
```

and additional for accordianList/plugin.js:
```
:14
allowedContent: '*{color};div(*)[*];h4(!collapsible-item*,panel*)[*];a(!collapsible-item*,panel*,collapsed)[*];span(!glyphicon*)[*];p;br;span[*];ul;ol;li;strong;em;u;table[*](*){*};tbody;theader;tr;td th[colspan,rowspan,nowrap]{border,border-width,vertical-align,width,color,white-space};hr;a;a(!href,*)[*];img(*)[*]'
```
