### ISSUE TITLE
Change allowedContent to allow links in Content

### ISSUE THREAD

**Issue by NullIsNot0** [pkerspe/ckeditor-bootstrap-collapsibleItem#9]
Allowed content should be on line 34 in plugin.js:

`allowedContent: "p;br;span[*];ul;ol;li;strong;em;u;table(*)[*];tbody;thead;tr;td;th;hr;a;a[*];img(*)[*];"`

**Comment by pkerspe** [comment]
Done in commit 7bd6b4a3c3a54fe86c4e8ea1878c788783cfbda6

**Comment by NullIsNot0** [comment]
Please don't forget to release new version, so CKEditor online builder can build correctly working version.
